"use client";

import { useEffect, useState } from "react";
import { useSitecopy } from "./LanguageProvider";
import type { SynopsisStat } from "./sitecopy";

export default function Synopsis() {
  const { synopsis } = useSitecopy();
  const [expandedImage, setExpandedImage] = useState<null | { src: string; alt: string }>(null);
  const [expandedStat, setExpandedStat] = useState<null | SynopsisStat>(null);
  // Responsive variants generated by seo-handoff at 480/768/1200 widths.
  // Grid cells render at ~250px (desktop 4-col) or ~50vw (mobile 2-col),
  // so 480w covers 2× desktop; 768w covers large tablets; 1200w = lightbox.
  const getSrcSet = (src: string) => {
    const base = src.replace(".webp", "");
    return `${base}-480w.webp 480w, ${base}-768w.webp 768w, ${base}-1200w.webp 1200w`;
  };
  const SYNOPSIS_SIZES = "(max-width: 700px) 50vw, 25vw";

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setExpandedImage(null);
        setExpandedStat(null);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, []);

  const highlightNames = (text: string) => {
    return text
      .replace(/Joe Kirby/g, '<strong class="highlight">Joe Kirby</strong>')
      .replace(/Lexi Taylor/g, '<strong class="highlight">Lexi Taylor</strong>')
      .replace(/"Mr\. Shiny"/g, '<strong class="highlight">"Mr. Shiny"</strong>');
  };

  return (
    <article className="synopsis" id="about">
      <h2 className="synopsisTitle">{synopsis.title}</h2>
      
      <div className="synopsisContent">
        <div className="synopsisText">
          <p dangerouslySetInnerHTML={{ __html: highlightNames(synopsis.body[0]) }} />
          <p dangerouslySetInnerHTML={{ __html: highlightNames(synopsis.body[1]) }} />
        </div>
        
        <div className="synopsisText">
          <p dangerouslySetInnerHTML={{ __html: highlightNames(synopsis.body[2]) }} />
          {synopsis.quote && (
            <blockquote className="synopsisQuote">
              <p>{synopsis.quote.text}</p>
              <cite>— {synopsis.quote.attribution}</cite>
            </blockquote>
          )}
        </div>
      </div>

      {synopsis.images && (
        <div className="synopsisImages">
          {synopsis.images.map((img, idx) => (
            <button
              key={idx}
              className="synopsisMediaButton"
              type="button"
              onClick={() => setExpandedImage({ src: img.src, alt: img.alt })}
              aria-label={`Expand image: ${img.alt}`}
            >
              <img
                src={img.src}
                srcSet={getSrcSet(img.src)}
                sizes={SYNOPSIS_SIZES}
                alt={img.alt}
                loading="lazy"
                decoding="async"
                width={1200}
                height={675}
              />
            </button>
          ))}
        </div>
      )}

      {synopsis.stats && (
        <div className="synopsisStats">
          {synopsis.stats.map((stat, idx) => (
            <button
              key={idx}
              className="synopsisStat synopsisStatButton"
              type="button"
              onClick={() => setExpandedStat({ value: stat.value, label: stat.label, tone: stat.tone })}
              // No aria-label: the visible value + label is the name. "Expand stat: <label> <value>"
              // reordered the words, so voice control and screen readers heard a different button
              // than the one on screen (label-content-name-mismatch); "button" already says it acts.
            >
              <div className={`statValue${stat.tone === "warning" ? " statValueWarning" : ""}`}>{stat.value}</div>
              <div className="statLabel">{stat.label}</div>
            </button>
          ))}
        </div>
      )}

      {expandedImage && (
        <div className="synopsisLightbox" role="dialog" aria-modal="true" onClick={() => setExpandedImage(null)}>
          <button
            className="synopsisLightboxClose"
            type="button"
            onClick={() => setExpandedImage(null)}
            aria-label={synopsis.closeImageAria}
          >
            ×
          </button>
          <img
            src={expandedImage.src.replace(".webp", "-1200w.webp")}
            srcSet={getSrcSet(expandedImage.src)}
            sizes="(max-width: 700px) 95vw, 80vw"
            alt={expandedImage.alt}
            className="synopsisLightboxImage"
            onClick={(e) => e.stopPropagation()}
            loading="lazy"
            decoding="async"
            width={1200}
            height={675}
          />
        </div>
      )}

      {expandedStat && (
        <div className="synopsisLightbox" role="dialog" aria-modal="true" onClick={() => setExpandedStat(null)}>
          <button
            className="synopsisLightboxClose"
            type="button"
            onClick={() => setExpandedStat(null)}
            aria-label={synopsis.closeStatAria}
          >
            ×
          </button>
          <div className="synopsisStatExpanded" onClick={(e) => e.stopPropagation()}>
            <div className={`statValue${expandedStat.tone === "warning" ? " statValueWarning" : ""}`}>{expandedStat.value}</div>
            <div className="statLabel">{expandedStat.label}</div>
          </div>
        </div>
      )}
    </article>
  );
}
